package com.zq.shop.web.mappers;

import com.zq.shop.web.bean.Address;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_address
     *
     * @mbg.generated
     */
    int insert(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_address
     *
     * @mbg.generated
     */
    int insertSelective(Address record);

    List<Address> findByLevelAndShengOrDi(@Param("level") String level, @Param("sheng") String sheng, @Param("di") String di);


}