package com.zq.shop.web.mappers;

import com.zq.shop.web.bean.Cart;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_cart
     *
     * @mbg.generated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_cart
     *
     * @mbg.generated
     */
    int insertSelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_cart
     *
     * @mbg.generated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cart record);

    Cart findOneByUserIdAndProductId(@Param("userId") Integer userId, @Param("productId") Integer productId);

    List<Cart> findByUserId(@Param("userId") Integer userId);

    int deleteByUserIdAndProductId(@Param("userId") Integer userId, @Param("productId") List<String> productId);

    int updateCheckedByUserIdAndProductId(@Param("updatedChecked")Integer updatedChecked,@Param("userId")Integer userId,@Param("productId")Integer productId);

    List<Cart> findByUserIdAndcheckedBetweenOrEqualTo(@Param("userId")Integer userId,@Param("minChecked")Integer minChecked,@Param("maxChecked")Integer maxChecked);



}