package com.zq.shop.web.mappers;

import com.zq.shop.web.bean.MomentsComment;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MomentsCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_moments_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_moments_comment
     *
     * @mbg.generated
     */
    int insert(MomentsComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_moments_comment
     *
     * @mbg.generated
     */
    int insertSelective(MomentsComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_moments_comment
     *
     * @mbg.generated
     */
    MomentsComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_moments_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MomentsComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_moments_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MomentsComment record);

    List<MomentsComment> findByMomentsId(@Param("momentsId")Integer momentsId);


}