package com.zq.shop.web.mappers;

import com.zq.shop.web.bean.OrderSettlements;

public interface OrderSettlementsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_order_settlements
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_order_settlements
     *
     * @mbg.generated
     */
    int insert(OrderSettlements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_order_settlements
     *
     * @mbg.generated
     */
    int insertSelective(OrderSettlements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_order_settlements
     *
     * @mbg.generated
     */
    OrderSettlements selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_order_settlements
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderSettlements record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_order_settlements
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderSettlements record);
}