package com.zq.shop.web.mappers;

import com.zq.shop.web.bean.Order;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_order
     *
     * @mbg.generated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_order
     *
     * @mbg.generated
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_order
     *
     * @mbg.generated
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Order record);


    Order findOneByUserIdAndOrderNo(@Param("userId") Integer userId, @Param("orderNo") Long orderNo);


    List<Order> findByUserId(@Param("userId") Integer userId);

    List<Order> find();

    Order findOneByOrderNo(@Param("orderNo") Long orderNo);
}

