package com.zq.shop.web.mappers;

import com.zq.shop.web.bean.ProductCategory;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_category
     *
     * @mbg.generated
     */
    int insert(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_category
     *
     * @mbg.generated
     */
    int insertSelective(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_category
     *
     * @mbg.generated
     */
    ProductCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductCategory record);


    List<ProductCategory> findByParentId(@Param("parentId")Integer parentId);


    List<Integer> findIdByParentId(@Param("parentId")Integer parentId);

}