package com.zq.shop.web.mappers;

import com.zq.shop.web.bean.Product;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_product
     *
     * @mbg.generated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_product
     *
     * @mbg.generated
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_product
     *
     * @mbg.generated
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Product record);

    List<Product> find();

    List<Product> findByUserId(@Param("userId") Integer userId);

    List<Product> selectByNameAndCategoryIdsOnSale(@Param("likeName") String productName
            , @Param("categoryIdList") List<Integer> categoryIdList);


    List<Product> findByNameLikeOrIdOnSale(@Param("likeName") String likeName, @Param("id") Integer id);


}