package com.zq.shop.web.mappers;

import com.zq.shop.web.bean.RongIMToken;
import org.apache.ibatis.annotations.Param;

public interface RongIMTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_rongim_token
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_rongim_token
     *
     * @mbg.generated
     */
    int insert(RongIMToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_rongim_token
     *
     * @mbg.generated
     */
    int insertSelective(RongIMToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_rongim_token
     *
     * @mbg.generated
     */
    RongIMToken selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_rongim_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RongIMToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_rongim_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RongIMToken record);

    RongIMToken findOneByUserId(@Param("userId")Integer userId);




}