package com.zq.shop.web.mappers;
import com.zq.shop.web.bean.Sequence;

import java.util.List;

public interface SequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_sequence
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_sequence
     *
     * @mbg.generated
     */
    int insert(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_sequence
     *
     * @mbg.generated
     */
    int insertSelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_sequence
     *
     * @mbg.generated
     */
    Sequence selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_sequence
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_sequence
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Sequence record);
    List<Sequence> find();


}