package com.zq.shop.web.mappers;

import com.zq.shop.web.bean.Shipping;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_shipping
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_shipping
     *
     * @mbg.generated
     */
    int insert(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_shipping
     *
     * @mbg.generated
     */
    int insertSelective(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_shipping
     *
     * @mbg.generated
     */
    Shipping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_shipping
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_shipping
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Shipping record);

    int deleteByIdAndUserId(@Param("id") Integer id, @Param("userId") Integer userId);

    int updateByShipping(Shipping shipping);

    Shipping findByUserIdAndId(@Param("userId") Integer userId, @Param("id") Integer id);

    Shipping findByUserIdAndIsDefault(@Param("userId") Integer userId);

    List<Shipping> findByUserId(@Param("userId") Integer userId);
}