package com.zq.shop.web.mappers;
import com.zq.shop.web.bean.Star;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_star
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_star
     *
     * @mbg.generated
     */
    int insert(Star record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_star
     *
     * @mbg.generated
     */
    int insertSelective(Star record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_star
     *
     * @mbg.generated
     */
    Star selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_star
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Star record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zq_star
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Star record);
    List<Star> findByStarIdAndtypeandUserId(@Param("starId")Integer starId,@Param("type")Integer type,@Param("userId")Integer userId);

    List<Star> findBystarIdandType(@Param("starId")Integer starId,@Param("type")Integer type);






}