package com.zq.shop.web.bean;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table zq_address
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_address.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_address.sheng
     *
     * @mbg.generated
     */
    private String sheng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_address.di
     *
     * @mbg.generated
     */
    private String di;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_address.xian
     *
     * @mbg.generated
     */
    private String xian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_address.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_address.level
     *
     * @mbg.generated
     */
    private String level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_address.code
     *
     * @return the value of zq_address.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_address.code
     *
     * @param code the value for zq_address.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_address.sheng
     *
     * @return the value of zq_address.sheng
     *
     * @mbg.generated
     */
    public String getSheng() {
        return sheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_address.sheng
     *
     * @param sheng the value for zq_address.sheng
     *
     * @mbg.generated
     */
    public void setSheng(String sheng) {
        this.sheng = sheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_address.di
     *
     * @return the value of zq_address.di
     *
     * @mbg.generated
     */
    public String getDi() {
        return di;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_address.di
     *
     * @param di the value for zq_address.di
     *
     * @mbg.generated
     */
    public void setDi(String di) {
        this.di = di;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_address.xian
     *
     * @return the value of zq_address.xian
     *
     * @mbg.generated
     */
    public String getXian() {
        return xian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_address.xian
     *
     * @param xian the value for zq_address.xian
     *
     * @mbg.generated
     */
    public void setXian(String xian) {
        this.xian = xian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_address.name
     *
     * @return the value of zq_address.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_address.name
     *
     * @param name the value for zq_address.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_address.level
     *
     * @return the value of zq_address.level
     *
     * @mbg.generated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_address.level
     *
     * @param level the value for zq_address.level
     *
     * @mbg.generated
     */
    public void setLevel(String level) {
        this.level = level;
    }
}