package com.zq.shop.web.bean;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table zq_moments_comment
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class MomentsComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_moments_comment.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_moments_comment.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_moments_comment.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   评论对象用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_moments_comment.follow_id
     *
     * @mbg.generated
     */
    private Integer followId;

    /**
     * Database Column Remarks:
     *   文章id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_moments_comment.moments_Id
     *
     * @mbg.generated
     */
    private Integer momentsId;

    /**
     * Database Column Remarks:
     *   评论内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_moments_comment.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * Database Column Remarks:
     *   评论内容图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_moments_comment.images
     *
     * @mbg.generated
     */
    private String images;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_moments_comment.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_moments_comment.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_moments_comment.id
     *
     * @return the value of zq_moments_comment.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_moments_comment.id
     *
     * @param id the value for zq_moments_comment.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_moments_comment.user_id
     *
     * @return the value of zq_moments_comment.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_moments_comment.user_id
     *
     * @param userId the value for zq_moments_comment.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_moments_comment.status
     *
     * @return the value of zq_moments_comment.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_moments_comment.status
     *
     * @param status the value for zq_moments_comment.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_moments_comment.follow_id
     *
     * @return the value of zq_moments_comment.follow_id
     *
     * @mbg.generated
     */
    public Integer getFollowId() {
        return followId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_moments_comment.follow_id
     *
     * @param followId the value for zq_moments_comment.follow_id
     *
     * @mbg.generated
     */
    public void setFollowId(Integer followId) {
        this.followId = followId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_moments_comment.moments_Id
     *
     * @return the value of zq_moments_comment.moments_Id
     *
     * @mbg.generated
     */
    public Integer getMomentsId() {
        return momentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_moments_comment.moments_Id
     *
     * @param momentsId the value for zq_moments_comment.moments_Id
     *
     * @mbg.generated
     */
    public void setMomentsId(Integer momentsId) {
        this.momentsId = momentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_moments_comment.content
     *
     * @return the value of zq_moments_comment.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_moments_comment.content
     *
     * @param content the value for zq_moments_comment.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_moments_comment.images
     *
     * @return the value of zq_moments_comment.images
     *
     * @mbg.generated
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_moments_comment.images
     *
     * @param images the value for zq_moments_comment.images
     *
     * @mbg.generated
     */
    public void setImages(String images) {
        this.images = images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_moments_comment.create_time
     *
     * @return the value of zq_moments_comment.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_moments_comment.create_time
     *
     * @param createTime the value for zq_moments_comment.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_moments_comment.update_time
     *
     * @return the value of zq_moments_comment.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_moments_comment.update_time
     *
     * @param updateTime the value for zq_moments_comment.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}