package com.zq.shop.web.bean;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table zq_order
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order.order_no
     *
     * @mbg.generated
     */
    private Long orderNo;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order.shipping_id
     *
     * @mbg.generated
     */
    private Integer shippingId;

    /**
     * Database Column Remarks:
     *   实际付款金额,单位是元,保留两位小数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order.payment
     *
     * @mbg.generated
     */
    private BigDecimal payment;

    /**
     * Database Column Remarks:
     *   支付类型,1-在线支付
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order.payment_type
     *
     * @mbg.generated
     */
    private Integer paymentType;

    /**
     * Database Column Remarks:
     *   运费,单位是元
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order.postage
     *
     * @mbg.generated
     */
    private Integer postage;

    /**
     * Database Column Remarks:
     *   订单状态:0-已取消-10-未付款，20-已付款，40-已发货，50-交易成功，60-交易关闭
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   支付时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order.payment_time
     *
     * @mbg.generated
     */
    private Date paymentTime;

    /**
     * Database Column Remarks:
     *   发货时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order.send_time
     *
     * @mbg.generated
     */
    private Date sendTime;

    /**
     * Database Column Remarks:
     *   交易完成时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     * Database Column Remarks:
     *   交易关闭时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order.close_time
     *
     * @mbg.generated
     */
    private Date closeTime;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order.id
     *
     * @return the value of zq_order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order.id
     *
     * @param id the value for zq_order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order.order_no
     *
     * @return the value of zq_order.order_no
     *
     * @mbg.generated
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order.order_no
     *
     * @param orderNo the value for zq_order.order_no
     *
     * @mbg.generated
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order.user_id
     *
     * @return the value of zq_order.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order.user_id
     *
     * @param userId the value for zq_order.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order.shipping_id
     *
     * @return the value of zq_order.shipping_id
     *
     * @mbg.generated
     */
    public Integer getShippingId() {
        return shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order.shipping_id
     *
     * @param shippingId the value for zq_order.shipping_id
     *
     * @mbg.generated
     */
    public void setShippingId(Integer shippingId) {
        this.shippingId = shippingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order.payment
     *
     * @return the value of zq_order.payment
     *
     * @mbg.generated
     */
    public BigDecimal getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order.payment
     *
     * @param payment the value for zq_order.payment
     *
     * @mbg.generated
     */
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order.payment_type
     *
     * @return the value of zq_order.payment_type
     *
     * @mbg.generated
     */
    public Integer getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order.payment_type
     *
     * @param paymentType the value for zq_order.payment_type
     *
     * @mbg.generated
     */
    public void setPaymentType(Integer paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order.postage
     *
     * @return the value of zq_order.postage
     *
     * @mbg.generated
     */
    public Integer getPostage() {
        return postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order.postage
     *
     * @param postage the value for zq_order.postage
     *
     * @mbg.generated
     */
    public void setPostage(Integer postage) {
        this.postage = postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order.status
     *
     * @return the value of zq_order.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order.status
     *
     * @param status the value for zq_order.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order.payment_time
     *
     * @return the value of zq_order.payment_time
     *
     * @mbg.generated
     */
    public Date getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order.payment_time
     *
     * @param paymentTime the value for zq_order.payment_time
     *
     * @mbg.generated
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order.send_time
     *
     * @return the value of zq_order.send_time
     *
     * @mbg.generated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order.send_time
     *
     * @param sendTime the value for zq_order.send_time
     *
     * @mbg.generated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order.end_time
     *
     * @return the value of zq_order.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order.end_time
     *
     * @param endTime the value for zq_order.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order.close_time
     *
     * @return the value of zq_order.close_time
     *
     * @mbg.generated
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order.close_time
     *
     * @param closeTime the value for zq_order.close_time
     *
     * @mbg.generated
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order.create_time
     *
     * @return the value of zq_order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order.create_time
     *
     * @param createTime the value for zq_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order.update_time
     *
     * @return the value of zq_order.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order.update_time
     *
     * @param updateTime the value for zq_order.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}