package com.zq.shop.web.bean;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table zq_order_settlements
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class OrderSettlements {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order_settlements.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order_settlements.settlementNo
     *
     * @mbg.generated
     */
    private Integer settlementno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order_settlements.settlementType
     *
     * @mbg.generated
     */
    private Integer settlementtype;

    /**
     * Database Column Remarks:
     *   店铺ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order_settlements.shopId
     *
     * @mbg.generated
     */
    private Integer shopid;

    /**
     * Database Column Remarks:
     *   结算金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order_settlements.settlementMoney
     *
     * @mbg.generated
     */
    private Long settlementmoney;

    /**
     * Database Column Remarks:
     *   订单实际金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order_settlements.orderMoney
     *
     * @mbg.generated
     */
    private Long ordermoney;

    /**
     * Database Column Remarks:
     *   0:未结算 1:已结算
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order_settlements.isFinish
     *
     * @mbg.generated
     */
    private Integer isfinish;

    /**
     * Database Column Remarks:
     *   总佣金
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order_settlements.totalCommission
     *
     * @mbg.generated
     */
    private Long totalcommission;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order_settlements.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_order_settlements.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order_settlements.Id
     *
     * @return the value of zq_order_settlements.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order_settlements.Id
     *
     * @param id the value for zq_order_settlements.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order_settlements.settlementNo
     *
     * @return the value of zq_order_settlements.settlementNo
     *
     * @mbg.generated
     */
    public Integer getSettlementno() {
        return settlementno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order_settlements.settlementNo
     *
     * @param settlementno the value for zq_order_settlements.settlementNo
     *
     * @mbg.generated
     */
    public void setSettlementno(Integer settlementno) {
        this.settlementno = settlementno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order_settlements.settlementType
     *
     * @return the value of zq_order_settlements.settlementType
     *
     * @mbg.generated
     */
    public Integer getSettlementtype() {
        return settlementtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order_settlements.settlementType
     *
     * @param settlementtype the value for zq_order_settlements.settlementType
     *
     * @mbg.generated
     */
    public void setSettlementtype(Integer settlementtype) {
        this.settlementtype = settlementtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order_settlements.shopId
     *
     * @return the value of zq_order_settlements.shopId
     *
     * @mbg.generated
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order_settlements.shopId
     *
     * @param shopid the value for zq_order_settlements.shopId
     *
     * @mbg.generated
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order_settlements.settlementMoney
     *
     * @return the value of zq_order_settlements.settlementMoney
     *
     * @mbg.generated
     */
    public Long getSettlementmoney() {
        return settlementmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order_settlements.settlementMoney
     *
     * @param settlementmoney the value for zq_order_settlements.settlementMoney
     *
     * @mbg.generated
     */
    public void setSettlementmoney(Long settlementmoney) {
        this.settlementmoney = settlementmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order_settlements.orderMoney
     *
     * @return the value of zq_order_settlements.orderMoney
     *
     * @mbg.generated
     */
    public Long getOrdermoney() {
        return ordermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order_settlements.orderMoney
     *
     * @param ordermoney the value for zq_order_settlements.orderMoney
     *
     * @mbg.generated
     */
    public void setOrdermoney(Long ordermoney) {
        this.ordermoney = ordermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order_settlements.isFinish
     *
     * @return the value of zq_order_settlements.isFinish
     *
     * @mbg.generated
     */
    public Integer getIsfinish() {
        return isfinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order_settlements.isFinish
     *
     * @param isfinish the value for zq_order_settlements.isFinish
     *
     * @mbg.generated
     */
    public void setIsfinish(Integer isfinish) {
        this.isfinish = isfinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order_settlements.totalCommission
     *
     * @return the value of zq_order_settlements.totalCommission
     *
     * @mbg.generated
     */
    public Long getTotalcommission() {
        return totalcommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order_settlements.totalCommission
     *
     * @param totalcommission the value for zq_order_settlements.totalCommission
     *
     * @mbg.generated
     */
    public void setTotalcommission(Long totalcommission) {
        this.totalcommission = totalcommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order_settlements.create_time
     *
     * @return the value of zq_order_settlements.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order_settlements.create_time
     *
     * @param createTime the value for zq_order_settlements.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_order_settlements.update_time
     *
     * @return the value of zq_order_settlements.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_order_settlements.update_time
     *
     * @param updateTime the value for zq_order_settlements.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}