package com.zq.shop.web.bean;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table zq_product
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Product {
    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_product.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   分类id,对应product_category表的主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_product.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_product.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   商品副标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_product.subtitle
     *
     * @mbg.generated
     */
    private String subtitle;

    /**
     * Database Column Remarks:
     *   产品主图,url相对地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_product.main_image
     *
     * @mbg.generated
     */
    private String mainImage;

    /**
     * Database Column Remarks:
     *   价格,单位-元保留两位小数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_product.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   库存数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_product.stock
     *
     * @mbg.generated
     */
    private Integer stock;

    /**
     * Database Column Remarks:
     *   商品状态.1-在售 2-下架 3-删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_product.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_product.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_product.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   图片地址,json格式,扩展用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_product.sub_images
     *
     * @mbg.generated
     */
    private String subImages;

    /**
     * Database Column Remarks:
     *   商品详情
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_product.detail
     *
     * @mbg.generated
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_product.id
     *
     * @return the value of zq_product.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_product.id
     *
     * @param id the value for zq_product.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_product.category_id
     *
     * @return the value of zq_product.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_product.category_id
     *
     * @param categoryId the value for zq_product.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_product.name
     *
     * @return the value of zq_product.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_product.name
     *
     * @param name the value for zq_product.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_product.subtitle
     *
     * @return the value of zq_product.subtitle
     *
     * @mbg.generated
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_product.subtitle
     *
     * @param subtitle the value for zq_product.subtitle
     *
     * @mbg.generated
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_product.main_image
     *
     * @return the value of zq_product.main_image
     *
     * @mbg.generated
     */
    public String getMainImage() {
        return mainImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_product.main_image
     *
     * @param mainImage the value for zq_product.main_image
     *
     * @mbg.generated
     */
    public void setMainImage(String mainImage) {
        this.mainImage = mainImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_product.price
     *
     * @return the value of zq_product.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_product.price
     *
     * @param price the value for zq_product.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_product.stock
     *
     * @return the value of zq_product.stock
     *
     * @mbg.generated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_product.stock
     *
     * @param stock the value for zq_product.stock
     *
     * @mbg.generated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_product.status
     *
     * @return the value of zq_product.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_product.status
     *
     * @param status the value for zq_product.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_product.create_time
     *
     * @return the value of zq_product.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_product.create_time
     *
     * @param createTime the value for zq_product.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_product.update_time
     *
     * @return the value of zq_product.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_product.update_time
     *
     * @param updateTime the value for zq_product.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_product.sub_images
     *
     * @return the value of zq_product.sub_images
     *
     * @mbg.generated
     */
    public String getSubImages() {
        return subImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_product.sub_images
     *
     * @param subImages the value for zq_product.sub_images
     *
     * @mbg.generated
     */
    public void setSubImages(String subImages) {
        this.subImages = subImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_product.detail
     *
     * @return the value of zq_product.detail
     *
     * @mbg.generated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_product.detail
     *
     * @param detail the value for zq_product.detail
     *
     * @mbg.generated
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }
}