package com.zq.shop.web.bean;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table zq_sequence
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Sequence {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_sequence.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_sequence.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_sequence.current_value
     *
     * @mbg.generated
     */
    private Integer currentValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_sequence._increment
     *
     * @mbg.generated
     */
    private Integer increment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_sequence.id
     *
     * @return the value of zq_sequence.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_sequence.id
     *
     * @param id the value for zq_sequence.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_sequence.name
     *
     * @return the value of zq_sequence.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_sequence.name
     *
     * @param name the value for zq_sequence.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_sequence.current_value
     *
     * @return the value of zq_sequence.current_value
     *
     * @mbg.generated
     */
    public Integer getCurrentValue() {
        return currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_sequence.current_value
     *
     * @param currentValue the value for zq_sequence.current_value
     *
     * @mbg.generated
     */
    public void setCurrentValue(Integer currentValue) {
        this.currentValue = currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_sequence._increment
     *
     * @return the value of zq_sequence._increment
     *
     * @mbg.generated
     */
    public Integer getIncrement() {
        return increment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_sequence._increment
     *
     * @param increment the value for zq_sequence._increment
     *
     * @mbg.generated
     */
    public void setIncrement(Integer increment) {
        this.increment = increment;
    }
}