package com.zq.shop.web.bean;

import com.fasterxml.jackson.annotation.JsonView;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table zq_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ShopUser {

    public interface UserSimpleView {
    }

    /**
     * Database Column Remarks:
     * 用户表id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_user.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * Database Column Remarks:
     * 用户名
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_user.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     * 用户密码，MD5加密
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_user.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * Database Column Remarks:
     * 性别
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_user.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     * Database Column Remarks:
     * 年龄
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_user.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     * Database Column Remarks:
     * 头像
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_user.image
     *
     * @mbg.generated
     */
    private String image;

    /**
     * Database Column Remarks:
     * 预留
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_user.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     * Database Column Remarks:
     * 角色0 超级管理员 2时商户 2 普通用户
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_user.role
     *
     * @mbg.generated
     */
    private Integer role;

    /**
     * Database Column Remarks:
     * 创建时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     * 最后一次更新时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_user.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_user.uid
     *
     * @return the value of zq_user.uid
     * @mbg.generated
     */
    @JsonView(UserSimpleView.class)
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_user.uid
     *
     * @param uid the value for zq_user.uid
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_user.username
     *
     * @return the value of zq_user.username
     * @mbg.generated
     */
    @JsonView(UserSimpleView.class)
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_user.username
     *
     * @param username the value for zq_user.username
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_user.password
     *
     * @return the value of zq_user.password
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_user.password
     *
     * @param password the value for zq_user.password
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_user.email
     *
     * @return the value of zq_user.email
     * @mbg.generated
     */
    @JsonView(UserSimpleView.class)
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_user.email
     *
     * @param email the value for zq_user.email
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_user.phone
     *
     * @return the value of zq_user.phone
     * @mbg.generated
     */
    @JsonView(UserSimpleView.class)
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_user.phone
     *
     * @param phone the value for zq_user.phone
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_user.sex
     *
     * @return the value of zq_user.sex
     * @mbg.generated
     */
    @JsonView(UserSimpleView.class)
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_user.sex
     *
     * @param sex the value for zq_user.sex
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_user.age
     *
     * @return the value of zq_user.age
     * @mbg.generated
     */
    @JsonView(UserSimpleView.class)
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_user.age
     *
     * @param age the value for zq_user.age
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_user.image
     *
     * @return the value of zq_user.image
     * @mbg.generated
     */
    @JsonView(UserSimpleView.class)
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_user.image
     *
     * @param image the value for zq_user.image
     * @mbg.generated
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_user.type
     *
     * @return the value of zq_user.type
     * @mbg.generated
     */
    @JsonView(UserSimpleView.class)
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_user.type
     *
     * @param type the value for zq_user.type
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_user.role
     *
     * @return the value of zq_user.role
     * @mbg.generated
     */
    @JsonView(UserSimpleView.class)
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_user.role
     *
     * @param role the value for zq_user.role
     * @mbg.generated
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_user.create_time
     *
     * @return the value of zq_user.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_user.create_time
     *
     * @param createTime the value for zq_user.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zq_user.update_time
     *
     * @return the value of zq_user.update_time
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zq_user.update_time
     *
     * @param updateTime the value for zq_user.update_time
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}